darcyWeb/config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  devise_scope :admin do
    get 'admin/login', to: 'devise/sessions#new', as: 'new_login'
    post 'admin/login', to: 'devise/sessions#create', as: 'login'
    get 'admin/logout', to: 'devise/sessions#destroy', as: 'logout'
    get 'admin/edit', to: 'devise/registrations#edit', as: 'edit_admin_registration'
    put 'admin/edit', to: 'registrations#update', as: 'admin_registration'
    # get 'admin/registration', to: 'devise/registrations#new', as: 'new_registration'
    # post 'admin/registration', to: 'devise/registrations#create', as: 'registration'
  end
   devise_for :admins #, skip: [:sessions, :registrations, :passwords]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'map#index'

  get 'about', to: 'about#index'
  
  get 'findme', to: 'map#index'

  get 'admin', to: 'admin#index'

  namespace :admin do
    resources :buildings, except: [:show]
    resources :rooms, except: [:show]
    resources :admins, except: [:show]
    resources :points, except: [:show]
    resources :plans, except: [:show]
  end

  namespace :map do
    namespace :search do
      get '/', action: 'search'
      get '/geo', action: 'search_geo'
    end

    namespace :data do
      get 'buildings', action: 'buildings'
      get 'building/:id', action: 'building'
      get 'room/:id', action: 'room', as: :room
      get 'rooms/:building_id', action: 'rooms'
      get 'bikes', action: 'bikes'
      get 'bathrooms', action: 'bathrooms'
      get 'snackbars', action: 'snackbars'
      get 'busstops', action: 'busstops'
      get 'entrances', action: 'entrances'
      get 'informationpoints', action: 'informationpoints'
    end
  end

  get 'map/data'
  get 'map/building/:id', to: 'map#building'
  get 'map/routes'

  #This route run the parse for catch the data of buildings and rooms of matriculaweb page
  #get 'parse', to: 'parser#index'

  get 'map/datapoint'
  get 'map/point/:id', to: 'map#point'

  get 'map/routes'
  get 'map/building'

  get 'map/point'

  # Provisory method to destroy points and buildings
  get 'admin/points/:id', to: 'admin/points#destroy'
  get 'admin/buildings/:id', to: 'admin/buildings#destroy'
end

darcyWeb/app/views/admin/admins/_form.html.erb
<div class="row" style="margin-top: 30px;">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <%= title %>
      </div>
      <div class="card-body">
        <%= form_for(admin, url: url, validate: true) do |f| %>
        <div class="row">
          <div class="form-group col-md-6">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control', placeholder: 'Máximo de 20 caracteres'%>
          </div>
          <div class="form-group col-md-6">
            <%= f.label :email %>
            <%= f.text_field :email, class: 'form-control', placeholder: 'Exemplo: seuemail@gmail.com' %>
          </div>
          <%= render 'form_password', f: f if %w(new create).include?(action_name) %>
          <div class="form-group col-md-6">
            <%= f.submit 'Salvar', class: 'btn btn-sm btn-success' %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

darcyWeb/app/views/admin/admins/_form_password.html.erb
<div class="form-group col-md-6">
	<%= f.label :password %>
	<%= f.password_field :password, class: 'form-control', placeholder: 'Mínimo de 6 caracteres' %>
</div>
<div class="form-group col-md-6">
	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation, class: 'form-control' %>
</div>

darcyWeb/app/views/admin/admins/edit.html.erb
<%= render 'form', title: 'Editar Administrador', admin: @admin, url: admin_admin_path %>

darcyWeb/app/views/admin/admins/index.html.erb
<div class="row" style="margin-top: 30px;">
    <div class="col-xs-12">
      <%= notice.html_safe unless notice.blank? %>
        <div class="card card-mini">
            <div class="card-header">
                <div class="card-title">Administradores</div>
                <ul class="card-action">
                    <li>
                        <!-- colocar link de new admin -->
                        <%= link_to '<i class="fa fa-plus"></i>'.html_safe, new_admin_admin_path %>
                    </li>
                </ul>
            </div>
            <div class="card-body no-padding table-responsive">
                <table class="table card-table">
                    <thead>
                        <tr>
                            <th>Email</th>
                            <th>Nome</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @admins.each do |admin| %>
                        <tr>
                            <td><%= admin.email %></td>
                            <td><%= admin.name %></td>
                            <td>
                                <%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_admin_admin_path(admin) %>
                                <%= link_to '<i class="fa fa-remove"></i>'.html_safe, admin_admin_path(admin), method: :delete, data: {
                                  'sweet-alert-confirm': 'Alerta',
                                  'confirm-button-text': 'Sim',
                                  'cancel-button-text': 'Cancelar',
                                  'text': 'Tem certeza que deseja apagar este administrador?'
                                } %>
                            </td>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

darcyWeb/app/views/admin/admins/new.html.erb
<%= render 'form', title: 'Criar Administrador', admin: @admin, url: admin_admins_path %>