darcyWeb/config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  devise_scope :admin do
    get 'admin/login', to: 'devise/sessions#new', as: 'new_login'
    post 'admin/login', to: 'devise/sessions#create', as: 'login'
    get 'admin/logout', to: 'devise/sessions#destroy', as: 'logout'
    get 'admin/edit', to: 'devise/registrations#edit', as: 'edit_admin_registration'
    put 'admin/edit', to: 'registrations#update', as: 'admin_registration'
    # get 'admin/registration', to: 'devise/registrations#new', as: 'new_registration'
    # post 'admin/registration', to: 'devise/registrations#create', as: 'registration'
  end
   devise_for :admins #, skip: [:sessions, :registrations, :passwords]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'map#index'

  get 'about', to: 'about#index'
  
  get 'findme', to: 'map#index'

  get 'admin', to: 'admin#index'

  namespace :admin do
    resources :buildings, except: [:show]
    resources :rooms, except: [:show]
    resources :admins, except: [:show]
    resources :points, except: [:show]
    resources :plans, except: [:show]
  end

  namespace :map do
    namespace :search do
      get '/', action: 'search'
      get '/geo', action: 'search_geo'
    end

    namespace :data do
      get 'buildings', action: 'buildings'
      get 'building/:id', action: 'building'
      get 'room/:id', action: 'room', as: :room
      get 'rooms/:building_id', action: 'rooms'
      get 'bikes', action: 'bikes'
      get 'bathrooms', action: 'bathrooms'
      get 'snackbars', action: 'snackbars'
      get 'busstops', action: 'busstops'
      get 'entrances', action: 'entrances'
      get 'informationpoints', action: 'informationpoints'
    end
  end

  get 'map/data'
  get 'map/building/:id', to: 'map#building'
  get 'map/routes'

  #This route run the parse for catch the data of buildings and rooms of matriculaweb page
  #get 'parse', to: 'parser#index'

  get 'map/datapoint'
  get 'map/point/:id', to: 'map#point'

  get 'map/routes'
  get 'map/building'

  get 'map/point'

  # Provisory method to destroy points and buildings
  get 'admin/points/:id', to: 'admin/points#destroy'
  get 'admin/buildings/:id', to: 'admin/buildings#destroy'
end

darcyWeb/app/models/room.rb
class Room < ApplicationRecord
  acts_as :location

  belongs_to :building

  has_many :schedules

  # types of rooms
  enum room_type: [ :classroom, :laboratory, :professor_room, :study_room, :amphitheater, :academic_center, :kitchen, :SAA, :others]
  translate_enum :room_type

  # validations
  validates :acronym, length: { maximum: 20 }, presence: true
  validates :building, presence: true
  validates :geo_data, presence: true
  validates :latitude, numericality: true, presence: true
  validates :level, numericality: { only_integer: true }, presence: true
  validates :longitude, numericality: true, presence: true
  validates :room_type, inclusion: { in: room_types.keys }
  validates :title, length: { maximum: 50 }, presence: true
end

darcyWeb/app/controllers/admin/rooms_controller.rb
class Admin::RoomsController < AdminController
  before_action :set_room, only: [:destroy, :edit, :update]
  before_action :set_room_types, :set_plans, only: [:new, :edit, :update, :create]

  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def edit
  end

  def update
    if @room.update(room_params)
      redirect_to admin_rooms_path, notice: helpers.alert_success('Sala editada com êxito.')
    else
      render :edit
    end
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to admin_rooms_path, notice: helpers.alert_success('Sala criada com êxito.')
    else
      render :new
    end
  end

  def destroy
    @room.destroy
    redirect_to admin_rooms_path, notice: helpers.alert_success('Sala excluída com êxito.')
  end

  private

  def set_plans
    @plans = Plan.includes(:building).all
  end

  def set_room_types
    @room_types = Room.translated_room_types
  end

  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:acronym, :title, :building_id, :room_type, :level, :latitude, :longitude, :geo_data)
  end
end

darcyWeb/app/views/admin/rooms/_form.html.erb
<div class="card">
    <div class="row">
        <div class="col-md-5">
            <div class="card-header">
                <%= title %>
            </div>
            <div class="card-body">
                <%= form_for(room, url: url, validate: true) do |f| %>
                <div class="row">
                    <div class="form-group col-md-6">
                        <%= f.label :acronym %>
                        <%= f.text_field :acronym, class: 'form-control' %>
                    </div>
                    <div class="form-group col-md-6">
                        <%= f.label :title %>
                        <%= f.text_field :title, class: 'form-control' %>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-6">
                        <%= f.label :building_id %>
                        <%= f.select :building_id, options_for_levels_with_plans(@plans, room.building, room.level), {}, { class: 'form-control' } %>
                    </div>
                    <div class="form-group col-md-6">
                        <%= f.label :room_type %>
                        <%= f.select :room_type, @room_types.map{ |translation, room_type| [translation, room_type] }, {}, { class: 'form-control' } %>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-6">
                        <%= f.label :latitude %>
                        <%= f.text_field :latitude, class: 'form-control' %>
                    </div>
                    <div class="form-group col-md-6">
                        <%= f.label :longitude %>
                        <%= f.text_field :longitude, class: 'form-control' %>
                    </div>
                </div>
                <div class="form-group">
                    <%= f.hidden_field :geo_data %>
                    <%= f.hidden_field :level %>
                    <%= f.submit 'Salvar', class: 'btn btn-sm btn-success', id: "Salvar"  %>
                </div>
                <% end %>
            </div>
        </div>
        <div class="col-md-7">
            <div id="map" style="float: left;"></div>
        </div>
    </div>
</div>

darcyWeb/app/views/admin/rooms/edit.html.erb
<%= render 'form', title: 'Editar Sala', room: @room, url: admin_room_path(@room) %>

darcyWeb/app/views/admin/rooms/index.html.erb
<div class="row" style="margin-top: 30px;">
    <div class="col-xs-12">
      <%= notice.html_safe unless notice.blank? %>
        <div class="card card-mini">
            <div class="card-header">
                <div class="card-title">Salas</div>
                <ul class="card-action">
                    <li>
                        <%= link_to '<i class="fa fa-plus"></i>'.html_safe, new_admin_room_path %>
                    </li>
                </ul>
            </div>
            <div class="card-body no-padding table-responsive">
                <table class="table card-table">
                    <thead>
                        <tr>
                            <th>Título</th>
                            <th>Sigla</th>
                            <th>Edifício</th>
                            <th>Nível</th>
                            <th>Tipo</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @rooms.each do |room| %>
                        <tr>
                            <td><%= room.title %></td>
                            <td><%= room.acronym %></td>
                            <td><%= room.building.acronym %></td>
                            <td><%= room.level %></td>
                            <td><%= room.translated_room_type %></td>
                            <td>
                                <%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_admin_room_path(room) %>
                                <%= link_to '<i class="fa fa-remove"></i>'.html_safe, admin_room_path(room), method: :delete, data: {
                                  'sweet-alert-confirm': 'Alerta',
                                  'confirm-button-text': 'Sim',
                                  'confirm-button-color': '#DD6B55',
                                  'cancel-button-text': 'Cancelar',
                                  'text': 'Tem certeza que deseja apagar esta sala?'
                                } %>
                            </td>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

darcyWeb/app/views/admin/rooms/new.html.erb
<%= render 'form', title: 'Criar Sala', room: @room, url: admin_rooms_path %>